// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNtd2WivX7C56ErJlBwar9SsynCJcBXU',
    appId: '1:573776737247:web:cb29c76b91a86747994a6a',
    messagingSenderId: '573776737247',
    projectId: 'hibiscus-flutter',
    authDomain: 'hibiscus-flutter.firebaseapp.com',
    storageBucket: 'hibiscus-flutter.firebasestorage.app',
    measurementId: 'G-66W8PDRXL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStbfv4fXIIFbCYw3lMumM0JFhg43OKSM',
    appId: '1:573776737247:android:06333d739fc1db72994a6a',
    messagingSenderId: '573776737247',
    projectId: 'hibiscus-flutter',
    storageBucket: 'hibiscus-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5nymzzJm1KjLe1EgA8my2qP4XxBW_xo',
    appId: '1:573776737247:ios:1f88104b1e1bfe7c994a6a',
    messagingSenderId: '573776737247',
    projectId: 'hibiscus-flutter',
    storageBucket: 'hibiscus-flutter.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr5nymzzJm1KjLe1EgA8my2qP4XxBW_xo',
    appId: '1:573776737247:ios:1f88104b1e1bfe7c994a6a',
    messagingSenderId: '573776737247',
    projectId: 'hibiscus-flutter',
    storageBucket: 'hibiscus-flutter.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmNtd2WivX7C56ErJlBwar9SsynCJcBXU',
    appId: '1:573776737247:web:b3331e75d0d23e93994a6a',
    messagingSenderId: '573776737247',
    projectId: 'hibiscus-flutter',
    authDomain: 'hibiscus-flutter.firebaseapp.com',
    storageBucket: 'hibiscus-flutter.firebasestorage.app',
    measurementId: 'G-S72C2275LT',
  );
}
